### ISSUE TITLE
Execution failed for task ':app:processDebugGoogleServices'.

### ISSUE THREAD

**Issue by AhsanSN** [AhsanSN/FamiChat-Android#3]
Cannot build the apk for android. Throws the following errors.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
'
> com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 4 path $.project_info.name
'
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
'
BUILD FAILED in 2s
    at ChildProcess.whenDone (C:\Users\Ahsan Ahmed\Documents\GitHub\FamiChat-Android\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:4380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by AhsanSN** [comment]
problem solved in the new branch "pre-build-famichat"
